### ISSUE TITLE
Pod init SDK (ObjectiveC)

### ISSUE THREAD

**Issue by Surko** [Ceskasporitelna/cs-core-sdk-ios#12]
Pri inicializovani SDK pomocou CocoaPods v ObjectiveC projekte dostaneme Locker framework do stavu kedy nie su pristupne dolezite objekty a metody pre pracu s Lockerom (napr. LockType, LockInfo, ...).

Riesil som tak, ze som do nastavenia podu v project.pbxproj (build settings) pridal 
**SWIFT_SWIFT3_OBJC_INFERENCE = On;**
To ale vytvori plno warningov typu:
_Swift initializer 'LockInfo.init(lockType:length:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint_

pravdaze by sa dalo vyriesit pridanim @objc pre konkretne triedy, volania, inity atd...

**Comment by hauseja3** [comment]
@Surko při založení testovacího objC projektu a přidání `CSCoreSDK`+`CSLockerUISDK` pomocí cocoapods jsme nenarazili na problém. Použitý `podfile`:

```
platform :ios, ’11.0’

target 'your-project' do
    
  use_frameworks!

	source 'https://github.com/Ceskasporitelna/cocoa-pods-specs.git'
	source 'https://github.com/CocoaPods/Specs.git'

	pod 'CSCoreSDK'
	pod 'CSLockerUI'

	post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

@Majkitos prosimtě případně mě doplň

**Comment by hauseja3** [comment]
Verze `CSCoreSDK 2.2.0` a `CSLockerUI 3.2.0` jsou objC compatible.

**Comment by Surko** [comment]
Vyzera OK.
Po inkludnuti tychto novych verzii nemam ziadny problem s chybajucimi objektami.

**Comment by jmachan** [comment]
Ok - after using new version, problem solved.
