### ISSUE TITLE
public var properties not inferred, Swift 4

### ISSUE THREAD

**Issue by Surko** [Ceskasporitelna/cs-core-sdk-ios#17]
Doteraz som stale skusal pody s kombinaciou nastaveni:

- swift 3.2 
- SWIFT_SWIFT3_OBJC_INFERENCE = On

Po vydani novej verzie uz nie je nutne nastavovat **SWIFT_SWIFT3_OBJC_INFERENCE = On** a chybajuce classy su uz viditelne. Ked pri novej verzii nadalej zostaneme na SWIFT 3.2 tak zacneme dostavat chyby pri inicializatoroch Errorov. Nasledne kvoli tejto chybe som presiel na Swift 4.
V tejto chvili mi kompilator vyhodil dalsiu sadu chyb.

`Property 'xy' not found on object of type LockerMigrationDataDTO`
`LockerMigrationDataDTO *data = [[LockerMigrationDataDTO alloc] init];`
`data.clientId = @""; // ERROR`
`data.deviceFingerprint = @""; // ERROR`
`data.encryptionKey = @""; // ERROR`
`data.oneTimePasswordKey = @""; // ERROR`
`data.refreshToken = @""; // ERROR`

Vo swift 4 totiz inferencia properties musi byt explicitne dana pridanim @objc (potencialne @objcMembers na classe)

**Comment by hauseja3** [comment]
@Surko díky, podíváme se na to. 👍
