### ISSUE TITLE
CSCoreSDK, iOS, nelze buildit aplikace v XCode 10

### ISSUE THREAD

**Issue by Saffin** [Ceskasporitelna/cs-core-sdk-ios#24]
Při buildění CSCoreSDK na iOS se nám v XCode10 zobrazují kompilační chyby, kvůli kterým nelze zbuildit aplikace, které tuto knihovnu integrují. Bylo by prosím možné knihovnu aktualizovat?
Přidávám screenshot:
![image](https://user-images.githubusercontent.com/31603572/45952686-16d30680-c008-11e8-9eec-5f1acee380f0.png)

**Comment by hauseja3** [comment]
@Saffin Ahoj,

podíváme se na to. Prosím @kirscfil zkontroluješ to?

**Comment by hauseja3** [comment]
@Saffin it is out. Thanks for patience.
