### ISSUE TITLE
Úprava lockeru na možnosť migrácie v aplikácii MůjStav

### ISSUE THREAD

**Issue by Surko** [Ceskasporitelna/cs-core-sdk-ios#4]
Ahojte,

Rovnako ako na platforme Android tak aj na iOS je nutne vyriesit ako premigrovat stavajuce riesenie registrovania/prihlasovania/odhlasovania z aplikacie Muj stav aby pouzilo LockerSDK, LockerUI.
Viac info a technicke detaily v mailu s Janom Hauserom.

Priorita je rovnaka ako pri Androide.

Dakujem

**Comment by hauseja3** [comment]
Solved in #5
